# Site settings
title: All Futures Are Contested
email: dee@deltaechoecho.com
description: Foresight, equality, social resilience
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://deltaechoecho.github.io" # the base hostname & protocol for your site
author: Dee Harding
street_address: Newspeak House, Bethnal Green Road
city: London
#state: 
zip_code: E2 7DG
country: United Kingdom
#phone: (716) 555-5555

icon: fa-map # Font Awesome class for your site's icon
icon_dd: fa-sun-o

# Social settings
github_url: https://github.com/deltaechoecho
instagram_url: https://www.instagram.com/dee.harding/
linkedin_url: https://www.linkedin.com/in/aeharding/
flickr_url: https://flickr.com/photos/umbriel
500px_url: https://500px.com/aeharding
# medium_url: https://medium.com/@deltaechoecho
# keybase_url: https://keybase.io/dee
# stackoverflow_url: https://stackoverflow.com/users/5244342/dee-harding
spotify_url: https://open.spotify.com/user/umbriel
#diaspora:
#facebook_url: 
#pinterest_url:
#slack_url:


# Build settings
markdown: kramdown
sass:
style: compressed
include: ['_pages']
collections:
  - external_feed
